# Project: nitas
# Makefile created by Embarcadero Dev-C++ 6.3

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = src/main.o src/vm/chunk.o src/vm/vm.o src/vm/imm.o src/compiler/compiler.o
LINKOBJ  = src/main.o src/vm/chunk.o src/vm/vm.o src/vm/imm.o src/compiler/compiler.o
LIBS     = -L"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/lib" -L"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/lib" -static-libgcc -std=c99
INCS     = -I"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/include" -I"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include" -I"include/" -I"include/vm/" -I"include/compiler"
CXXINCS  = -I"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/include" -I"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include" -I"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++" -I"include/" -I"include/vm/" -I"include/compiler"
BIN      = nitas.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
DEL      = C:\Program Files (x86)\Embarcadero\Dev-Cpp\DevCpp.exe INTERNAL_DEL

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${DEL} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

src/main.o: src/main.c
	$(CC) -c src/main.c -o src/main.o $(CFLAGS)

src/vm/chunk.o: src/vm/chunk.c
	$(CC) -c src/vm/chunk.c -o src/vm/chunk.o $(CFLAGS)

src/vm/vm.o: src/vm/vm.c
	$(CC) -c src/vm/vm.c -o src/vm/vm.o $(CFLAGS)

src/vm/imm.o: src/vm/imm.c
	$(CC) -c src/vm/imm.c -o src/vm/imm.o $(CFLAGS)

src/compiler/compiler.o: src/compiler/compiler.c
	$(CC) -c src/compiler/compiler.c -o src/compiler/compiler.o $(CFLAGS)
